# Generated by Django 3.1.2 on 2020-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='media/images/14358.jpg', upload_to='images'),
        ),
    ]
